---
title: "Collaborations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Michigan State University** <br>
[David Lowry](https://directory.natsci.msu.edu/Directory/Profiles/Person/102338) (Associate Professor) and Ali Soltani (Postdoctoral Fellow) <br>
Collaboration on the effect of heat stress on dry bean reproductive physiology. <br>
Resulted in 2 publications: <br>
[Santiago et al. (2021)](https://onlinelibrary.wiley.com/doi/full/10.1111/pce.14057),
[Soltani et al. (2021)](https://link.springer.com/article/10.1186/s12870-021-02837-6)
<br>

[Rufus Isaacs](https://www.canr.msu.edu/people/rufus_isaacs) and Jenna Walters (PhD candidate) <br>
Collaboration on measuring highbush blueberry pollen metabolites (protein, carbohydrates, amino acids) post heat-stress treatment. <br>
Publication in preparation. <br>
<br>

**Technical University of Berlin** <br>
[Maik Lucas](https://www.tu.berlin/en/boku/about/maik-lucas) (Postdoctoral fellow, now Assistant Professor at Technical University of Berlin) <br>
Collaboration on tracking of radiolabeled carbon to soil profile.  <br>
Resulted in 1 publication: [Lucas et al. (2023)](https://nph.onlinelibrary.wiley.com/doi/full/10.1111/nph.19159)
<br>

**Uniersity of Minnesota** <br>
[John M. Ward](https://cbs.umn.edu/directory/john-m-ward) (Professor) <br>
Collaboration on functional characterization ofin yeast of a novel common bean sucrose transporter. <br>
Resulted in 1 publication: [Santiago, Ward, Sharkey (2020)](https://onlinelibrary.wiley.com/doi/full/10.1002/pld3.260)
<br>

**University of Florida** <br>
[Christopher I Vincent](https://crec.ifas.ufl.edu/people/faculty/christopher-vincent/) <br>
Collaboration on phloem sap flux disruption in Huanglongbing-infected citrus. <br>
Resulted in 1 publication: [Welker et al. (2022)](https://academic.oup.com/treephys/article/42/2/379/6382532)